illusion:
  database_location: "./inventory.db"
  discord:
    token: ""
    server_id: 
    fourm_id: 

  terminal:
    log_to_term: false

  printer:
    niimbot:
      enabled: true 
      port: ""
      font_path: ""
      font_size: 14